### ISSUE TITLE
Weird missing CSS bug

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#119]
@TeffenEllis I can’t figure out what’s going on here, hopefully you can help.

Repro:

1. Visit [https://eager.io/blog/introducing-embedbox-open-source-embed-code-ui/](https://eager.io/blog/introducing-embedbox-open-source-embed-code-ui/).
2. Click the modal demo button.
3. Close the modal.
4. Click the WordPress target entry in the inline demo.
5. Observe:

<img width=400 src=https://cloud.githubusercontent.com/assets/154613/18573206/498b6726-7b8f-11e6-8adc-3c384191e04e.png>

**Comment by adamschwartz** [comment]
p.s. That blog post will look less weird when the cache busts. 👀

**Comment by TeffenEllis** [comment]
@adamschwartz, 

This behavior is the result of two EmbedBox instances existing at the same time.
The data store keeps a reference to the instance's iframe. The store reference is kept on the `BaseComponent` constructor which is common among all EmbedBox instances. Depending on which EmbedBox instance is created last, that one will take control.

Component stylesheets work in a similar way. 
https://github.com/EagerIO/EmbedBox/blob/master/app/components/base-component.js#L20-L30

Rather than insert the same styles over and over every time a component is constructed, we check if the `<style>` is already in the iframe `<head>`.  This is where the fight for control takes effect.

Given this is deep in the architecture of the app, I think two tasks are fitting.

1. When a EmbedBox is created, any should be destroyed.
2. Use an iframe for the inline blog demo.

Thoughts?

**Comment by TeffenEllis** [comment]
@adamschwartz,

I did some meditation on this and there is a third option. The EmbedBox components share a common store reference inherited from `BaseComponent`. Given that only a few components consume the store directly, we could go from the implicit relationship to setting the reference on element creation.

Something like this perhaps,

```javascript
import Application from "components/application"
import {createStore} from "lib/store"

class EmbedBox {
  constructor(spec) {
    const store = createStore(spec)

    new Application({foo: 'bar', store})    
  }
}
```

We'd have to pass this reference down as far as we need it but it would fix the issue.

Thoughts?

Cheers

**Comment by adamschwartz** [comment]
Sounds good to me! 🚀
