### ISSUE TITLE
“Deep linking” API

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#26]
This may already exist in another form, but I think we need to have a really clear way of letting EmbedBox implementers share links to specific docs pages with their users.

e.g.
http://drift.com/install/#/path/to/embedbox/wordpress/docs
http://drift.com/install?embedBoxDocs=path/to/embedbox/wordpress/docs
etc.

**Comment by TeffenEllis** [comment]
At the moment we have an `initialTarget` option. I'm fond of this approach since it's consistent with our other options, and doesn't interfere with a user's existing route handler.

There's a soon to be added feature that lets the user specify and order the visible targets. It'd be slick to omit the initial search page when there's only one target visible.

**Comment by adamschwartz** [comment]
So the idea then would be that it’s left to the implementer to decide how preserve state in the URL, if at all?

**Comment by zackbloom** [comment]
@TeffenEllis why not look at `url.fragment`, and if it happens to be `embed/<target>` navigate to that by default? Then we could have another option for if we should update the fragment when the user chooses a target which is default false.

**Comment by TeffenEllis** [comment]
I've fleshed out a routing with a mix of simple but configurable. The developer can disable the feature. A v2 version can specify something like `{routing: "readonly"}` like Zack suggested 🐳
