### ISSUE TITLE
Confusing behavior for `downloadURL` and `embedCode` both specified

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#56]
From the source:

```javascript
  get copyText() {
    if (this.downloadURL) return `<script src="${this.downloadURL}"></script>`

    return this.config.embedCode || this.store.embedCode
  }
```

This is resulting in this for Weebly (on the homepage):

![image](https://cloud.githubusercontent.com/assets/154613/17631148/d838d716-6090-11e6-8ac2-110fddb864f8.png)

I’m thinking that maybe the logic here is backwards? Like if an `embedCode` is provided, use that, and only if there is no `embedCode` but there is a `downloadURL` should we revert to the concatenation?

Also, in the concatenation, we should probably strip the protocol, right? 
http://embed.books.eager.io/script-tag.html#https

cc @zackbloom

**Comment by TeffenEllis** [comment]
@adamschwartz, it's an interesting question.

We briefly chatted about what's the expected behavior when only a `downloadURL` is configured. My feeling is that a the config wide `downloadURL` is odd fitting since plugins are unique to targets. It should be scoped to the particular target. We already support scoped target configs overriding the global config 🐳 

Our most basic config:

```javascript
new EmbedBox({
  embedCode: "<script src='http://example.com/foo.js</script>"
})
```

This example would only show targets that support an `embedCode` (all of them?)

A plugin config:

```javascript
new EmbedBox({
  targets: {
    wordpress: {
      downloadURL: "http://example.com/wordpress.zip"
    }
  }
})
```

This example would only show a single target, WordPress.

This also brings up our `visibleTargets` property. I'm leaning toward it being confusing. `visibleTargets` does double duty of visibility and ordering. @zackbloom suggested a `priority` option awhile back. I think it'd be uncommon for a developer to hide a particular target, but if needed that can be arranged.

```javascript
new EmbedBox({
  targets: {
    wordpress: {
      downloadURL: "http://example.com/wordpress.zip",
      priority: 1
    },
    joomla: {
      downloadURL: "http://example.com/joomla.zip",
      priority: 2
    },
    wix: {
      visible: false
    }
  }
})
```

Thoughts?

**Comment by adamschwartz** [comment]
So the idea then would be to remove the global `downloadURL` option which the demo currently uses?

**Comment by TeffenEllis** [comment]
Yep. Given how odd it behaves, I'd say it makes sense.

**Comment by adamschwartz** [comment]
Sounds good. Do you still think this logic is correct?

```
  get copyText() {
    if (this.downloadURL) return `<script src="${this.downloadURL}"></script>`

    return this.config.embedCode || this.store.embedCode
  }
```

**Comment by TeffenEllis** [comment]
Probably not for the usual flow. I think that targets with `downloadURLs` will either be plugin oriented where it's about the software specific flow of uploading some file. 

A modified version might make sense for the generic target since it can have a combination `downloadURL` and script to copy.

**Comment by TeffenEllis** [comment]
Progress update:

The latest sorting logic is up and should be much easier to understand since it takes after the install.json `order` concept.
http://embedbox.io/#ordering
