### ISSUE TITLE
Better associate docs 'run' buttons with the sections they run

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#98]
One option is to move the buttons into the corner (I think top right might actually be best), and lighten the background of the runnable code areas a bit more:

![image](https://cloud.githubusercontent.com/assets/55347/18360891/db3830e0-75cd-11e6-9f6b-a67c99db91bd.png)

**Comment by adamschwartz** [comment]
Thanks!

**Comment by adamschwartz** [comment]
After trying this out for a bit, I felt that putting the buttons on the bottom didn’t work because they interacted with the horizontal scrollbar.

For design/development, I recommend setting “Show scrollbars” to “Always” in System Preferences, as it makes issues like these more obvious.

<img width=300 src=https://cloud.githubusercontent.com/assets/154613/18362883/b0021726-75d5-11e6-814e-60c13261f1b8.png>

I did however increase the contrast of the code block, which should help with the association, and improve the scrollbar styling. https://github.com/EagerIO/EmbedBox/commit/7f1fe21aca75b009a9f46924bbdab14fbc17e38a

**Comment by zackbloom** [comment]
Is putting them in the top right, but more tightly connected with the edge of the box like in the example an option?

**Comment by adamschwartz** [comment]
I’ll show you what that looks like. I tried that myself in my iterations just now and didn’t love it, but we’ll see what you think ;)

**Comment by zackbloom** [comment]
Thx, I appreciate it!

**Comment by adamschwartz** [comment]
A few options. Last one is current.

![image](https://cloud.githubusercontent.com/assets/154613/18363352/bf43622e-75d7-11e6-9795-10abe467e564.png)

![image](https://cloud.githubusercontent.com/assets/154613/18363378/e4270d84-75d7-11e6-8c0b-a656d5869138.png)

![image](https://cloud.githubusercontent.com/assets/154613/18363448/310b1b7c-75d8-11e6-81c5-257254519597.png)

![image](https://cloud.githubusercontent.com/assets/154613/18363553/931a7d12-75d8-11e6-8368-6505a7ff34b3.png)

![image](https://cloud.githubusercontent.com/assets/154613/18363564/9d5ab0f8-75d8-11e6-9539-4b48f02783e0.png)

![image](https://cloud.githubusercontent.com/assets/154613/18363403/f497e828-75d7-11e6-938b-64951a9df1d0.png)

**Comment by adamschwartz** [comment]
Oddly enough, my favorite is now this one:

<img src=https://cloud.githubusercontent.com/assets/154613/18363553/931a7d12-75d8-11e6-8368-6505a7ff34b3.png>

**Comment by adamschwartz** [comment]
Let me know!

**Comment by zackbloom** [comment]
For me any of the options which move the buttons outside of the code area break the association.  Also for me, having the padding around the buttons makes it hard to tell this isn't a part of the code sample, but is meta.

My personal favorites are the first two:

![image](https://cloud.githubusercontent.com/assets/55347/18363830/c5b49932-75d9-11e6-8633-b50ecafedadd.png)

and

**Comment by adamschwartz** [comment]
After much deliberation we have decided to go with this:

![image](https://cloud.githubusercontent.com/assets/154613/18367962/8437ab86-75eb-11e6-8142-6937c601f1a1.png)
